### ISSUE TITLE
/corrected_odom topic published sensor_msgs::PointCloud2 instead of nav_msgs::Odometry

### ISSUE THREAD

**Issue by AmirulJ97** [engcang/FAST-LIO-SAM#5]
Dear Dr. Eungchang-Mason-Lee,

First and foremost, I want to express my gratitude for your incredible work on the FAST-LIO-SAM package. It's been an invaluable tool for my project, and I truly appreciate the effort you've put into it.

Now, I have a question regarding the package's behavior. I've been using this package and have noticed that the /corrected_odom topic is currently publishing messages of type sensor_msgs::PointCloud2. However, based on the package's functionality, I expected it to publish nav_msgs::Odometry messages instead. 

1. Is there a specific reason why the /corrected_odom topic is publishing sensor_msgs::PointCloud2 messages instead of nav_msgs::Odometry as expected?
2. Is there a recommended modification or workaround to make /corrected_odom publish nav_msgs::Odometry messages?
I appreciate your help in resolving this matter. Thank you for your support.

**Comment by engcang** [comment]
Hi @AmirulJ97.
Thank you for your interest in my work.

I think your wanted topic is published as `geometry_msgs::PoseStamped` here - https://github.com/engcang/FAST-LIO-SAM/blob/master/fast_lio_sam/src/callbacks.cpp#L37 and the publisher is defined here - https://github.com/engcang/FAST-LIO-SAM/blob/master/fast_lio_sam/src/constructor.cpp#L66.

This topic is publishing corrected real-time odometry, but only the most recent one.

I hope this could be the answer for your question.
Otherwise, If you have further questions, feel free to ask.

**Comment by AmirulJ97** [comment]
Dear Dr. Eungchang-Mason-Lee,

Thank you very much for the answer. Hence, Im only need to change the geometry_msgs::PoseStamped to nav_msgs::Odometry right? May I know which one of the topic that publish the corrected pointcloud? Is it /corrected_current_pcd topic?

**Comment by engcang** [comment]
Hi @AmirulJ97 
Yes, if you want to get the real time corrected pose as odometry, change the type from PoseStamped into Odometry.
And yes, /corrected_current_pcd topic is the corrected pointcloud.
